version: "3.7"

services:
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-4
    volumes:
      - "./statsd.config.js:/opt/statsd/config.js:ro"
      - "./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf:ro"
      - "./graphite:/opt/graphite/storage/:rw"
    ports:
      - "8080:8080"
      - "8125:8125/udp"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8081:3000"
    volumes:
      - "grafana_config:/var/lib/grafana"
    depends_on:
      - graphite

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    command: >
      -storage_driver="statsd"
      -storage_driver_host="graphite:8125"
      -storage_driver_db="cadvisor"
      -storage_driver_buffer_duration="10s"
      --enable_metrics=cpu,cpuLoad,disk,diskIO,memory,network
    depends_on:
      - graphite
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    devices:
      - "/dev/kmsg"

  rabbitmq:
    image: rostov_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  worker:
    image: grid_search_scala_worker
    depends_on:
      - rabbitmq
      - graphite
    volumes:
      - "./containers/worker/src:/app/src"
      - "./containers/worker/build.sbt:/app/build.sbt"
      - "./containers/worker/project/build.properties:/app/project/build.properties"
      - "./containers/worker/project/plugins.sbt:/app/project/plugins.sbt"
      - "~/.ivy2:/root/.ivy2"
    deploy:
      replicas: 4
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=worker_{{.Task.Slot}}

  manager:
    image: grid_search_scala_manager
    depends_on:
      - rabbitmq
      - graphite
    volumes:
      - "./containers/manager/src/:/app/src"
      - "./containers/manager/build.sbt:/app/build.sbt"
      - "./containers/manager/project/build.properties:/app/project/build.properties"
      - "./containers/manager/project/plugins.sbt:/app/project/plugins.sbt"
      - "~/.ivy2:/root/.ivy2"
    deploy:
      restart_policy:
        condition: none
    environment:
      - LOCAL=${LOCAL}
      - NODE_ID=manager

volumes:
  grafana_config:
    driver: local