{
 "title": "Basic Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Per node throughput - 10m window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 1 },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(stats.*.results_produced, 'avg'), '10min'), 'mean')"
    },
    {
     "target": "alias(movingAverage(aggregate(stats.*.results_produced, 'max'), '10min'), 'max')"
    },
    {
     "target": "alias(movingAverage(aggregate(stats.*.results_produced, 'min'), '10min'), 'min')"
    }
   ]
  },
  {
   "title": "Measured Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "target": "groupByNodes(stats.gauges.cadvisor.gs_scala_worker.*.*.memory_usage, 'count')"
    }
   ]
  },
  {
   "title": "Combined throughput - 10m window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 9 },
   "targets": [
    {
     "target": "alias(movingAverage(groupByNode(stats.*.results_produced, 4, 'sum'), '10min'), 'mean')"
    },
    {
     "target": "alias(movingMax(groupByNode(stats.*.results_produced, 4, 'sum'), '10min'), 'max')"
    },
    {
     "target": "alias(movingMin(groupByNode(stats.*.results_produced, 4, 'sum'), '10min'), 'min')"
    }
   ]
  },
  {
   "title": "Coefficient of variation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$F/$E", "type": "math" }
   ]
  },
  {
   "title": "Memory Usage (Workers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.gs_scala_worker.*.*.memory_usage, 4, 'sum'), 'average'), '1min'), 'mean')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.gs_scala_worker.*.*.memory_usage, 4, 'sum'), 'max'), '1min'), 'max')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.gs_scala_worker.*.*.memory_usage, 4, 'sum'), 'min'), '1min'), 'min')"
    }
   ]
  },
  {
   "title": "Memory Usage (Worker 1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.gs_scala_worker.1.*.memory_usage, 4, 'sum'), 'average'), 'mean')"
    },
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.gs_scala_worker.1.*.memory_usage, 4, 'sum'), 'max'), 'max')"
    },
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.gs_scala_worker.1.*.memory_usage, 4, 'sum'), 'min'), 'max')"
    }
   ]
  },
  {
   "title": "CPU Usage (Workers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$D/$E", "type": "math" },
    { "expression": "$G/$H", "type": "math" }
   ]
  }
 ]
}